# Generated by Django 4.2.18 on 2025-06-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='customervisit',
            name='items_bought',
            field=models.ManyToManyField(to='items.item'),
        ),
    ]
